---
title: "HW 1"
author: "Oumayma Ben Aoun"
date: "Data 2401"
output: 
  html_document: 
    fig_caption: true
    fig_width: 25
    fig_height: 25
    highlight: pygments
    theme: journal
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

- datasaurus_dozen_wide has 142 rows and zero columns (columns are not stated in datasaurus_dozen_wide file)

- There are 26 variables in the datasaurus_dozen_wide file: 

```
away_x: x-values for the away dataset

away_y: y-values for the away dataset

bullseye_x: x-values for the bullseye dataset

bullseye_y: y-values for the bullseye dataset

circle_x: x-values for the circle dataset

circle_y: y-values for the circle dataset

dino_x: x-values for dinosaur dataset!

dino_y: y-values for dinosaur dataset!

dots_x: x-values for the dots dataset

dots_y: y-values for the dots dataset

h_lines_x: x-values for the h_lines dataset

h_lines_y: y-values for the h_lines dataset

high_lines_x: x-values for the high_lines dataset

high_lines_y: y-values for the high_lines dataset

slant_down_x: x-values for the slant_down dataset

slant_down_y: y-values for the slant_down dataset

slant_up_x: x-values for the slant_up dataset

slant_up_y: y-values for the slant_up dataset

star_x: x-values for the star dataset

star_y: y-values for the star dataset

v_lines_x: x-values for the v_lines dataset

v_lines_y: y-values for the v_lines dataset

wide_lines_x: x-values for the wide_lines dataset

wide_lines_y: y-values for the wide_lines dataset

x_shape_x: x-values for the x_shape dataset

x_shape_y: y-values for the x_shape dataset

```

### Exercise 2

```{r plot-dino}
# Plot 
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()

```


```{r cor-dino}
# Calculate the correlation 
dino_correlation <- dino_data %>%
  summarize(r = cor(x, y))
print(dino_correlation) 

```


### Exercise 3

```{r plot-star}
# Plot
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

 

```{r cor-star} 
# Calculate the correlation
star_correlation <- star_data %>%
  summarize(r = cor(x, y))
print(star_correlation) 

#The two correlation values are not identical; difference of 0.0015, the difference between them is minimal and likely doesn't indicate a significant change in the underlying relationship between the variables.

``` 

 

### Exercise 4

```{r plot-circle}
# Plot  
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()

```

```{r cor-circle}
# Calculate the correlation
circle_correlation <- circle_data %>%
  summarize(r = cor(x, y))
print(circle_correlation) 

#While the two correlation values are not identical; difference of −0.0038, the difference between them is minimal and likely doesn't indicate a significant change in the underlying relationship between the variables.

```

### Exercise 5

```{r plot}

#  Plot all Data-Sets at Once 

ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset)) +
  geom_point() +
  facet_wrap(~ dataset, ncol = 3) + 
  theme(legend.position = "none")

# Using group_by function, generate all the summary correlation coefficients.

datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)

```

```
## summarise() ungrouping output (override with .groups argument)
## # A tibble: 13 x 2
## dataset r
##
## 1 away -0.0641
## 2 bullseye -0.0686
## 3 circle -0.0683
## 4 dino -0.0645
## 5 dots -0.0603
## 6 h_lines -0.0617
## 7 high_lines -0.0685
## 8 slant_down -0.0690
## 9 slant_up -0.0686
## 10 star -0.0630
## 11 v_lines -0.0694
## 12 wide_lines -0.0666
## 13 x_shape -0.0656
```

